---
title: "Projekt Zaliczeniowy"
author: "Jakub Rękas, Ernest Szlamczyk"
output: pdf_document
---

## Wstęp
Projekt ten ma na celu proste opracowanie statystyczne wyników porównania działania wybranych algorytmów minimalizacji stochastycznej.    

Do porównania wybraliśmy algorytmy:  
* Poszukikwanie przypadkowe (Pure Random Search, PRS)  
* Metoda wielokrotnego startu (multi-start, MS)  

Dodatkowo użyliliśmy funkji:  
* Ackley’a  
* Rastrigina  

## WYNIKI

```{r echo=FALSE}
test <- as.vector(read.csv("./data/ackley2Dms.csv"))$x
hist(test, main="Funkcja Ackleya 2D, MS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,70), xlim = c(0,12)
     )
```

```{r echo=FALSE}
test <- as.vector(read.csv("./data/ackley2Dprs.csv"))$x
hist(test, main="Funkcja Ackleya 2D, PRS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,40), xlim = c(0,8)
     )
```

```{r echo=FALSE}
test <- as.vector(read.csv("./data/ackley10Dms.csv"))$x
hist(test, main="Funkcja Ackleya 10D, MS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,50), xlim = c(14,20)
     )
```

```{r echo=FALSE}
test <- as.vector(read.csv("./data/ackley10Dprs.csv"))$x
hist(test, main="Funkcja Ackleya 10D, PRS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,40), xlim = c(15,20)
     )
```

```{r echo=FALSE}
test <- as.vector(read.csv("./data/ackley20Dms.csv"))$x
hist(test, main="Funkcja Ackleya 20D, MS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,40), xlim = c(17,20)
     )
```

```{r echo=FALSE}
test <- as.vector(read.csv("./data/ackley20Dprs.csv"))$x
hist(test, main="Funkcja Ackleya 20D, PRS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,50), xlim = c(18,21)
     )
```

```{r echo=FALSE}
test <- as.vector(read.csv("./data/rastrigin2Dms.csv"))$x
hist(test, main="Funkcja Rastrigina 2D, MS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,70), xlim = c(0,1)
     )
```

```{r echo=FALSE}
test <- as.vector(read.csv("./data/rastrigin2Dprs.csv"))$x
hist(test, main="Funkcja Rastrigina 2D, PRS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,40), xlim = c(0,4)
     )
```

```{r echo=FALSE}
test <- as.vector(read.csv("./data/rastrigin10Dms.csv"))$x
hist(test, main="Funkcja Rastrigina 10D, MS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,40), xlim = c(0,40)
     )
```

```{r echo=FALSE}
test <- as.vector(read.csv("./data/rastrigin10Dprs.csv"))$x
hist(test, main="Funkcja Rastrigina 10D, PRS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,30), xlim = c(40,100)
     )
```

```{r echo=FALSE}
test <- as.vector(read.csv("./data/rastrigin20Dms.csv"))$x
hist(test, main="Funkcja Rastrigina 20D, MS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,30), xlim = c(30,100)
     )
```

```{r echo=FALSE}
test <- as.vector(read.csv("./data/rastrigin20DPRS.csv"))$x
hist(test, main="Funkcja Rastrigina 20D, PRS", 
     xlab = "Znaleziona wartość minimum", ylab = "Ilość wystąpień", labels = TRUE,
     ylim = c(0,40), xlim = c(160,260)
     )
```

```{r echo=FALSE}
a2ms <- as.vector(read.csv("./data/ackley2Dms.csv"))$x
a2prs <- as.vector(read.csv("./data/ackley2Dprs.csv"))$x
a10ms <- as.vector(read.csv("./data/ackley10Dms.csv"))$x
a10prs <- as.vector(read.csv("./data/ackley10Dprs.csv"))$x
a20ms <- as.vector(read.csv("./data/ackley20Dms.csv"))$x
a20prs <- as.vector(read.csv("./data/ackley20Dprs.csv"))$x
r2ms <- as.vector(read.csv("./data/rastrigin2Dms.csv"))$x
r2prs <- as.vector(read.csv("./data/rastrigin2Dprs.csv"))$x
r10ms <- as.vector(read.csv("./data/rastrigin10Dms.csv"))$x
r10prs <- as.vector(read.csv("./data/rastrigin10Dprs.csv"))$x
r20ms <- as.vector(read.csv("./data/rastrigin20Dms.csv"))$x
r20prs <- as.vector(read.csv("./data/rastrigin20Dprs.csv"))$x


boxplot(a2ms,a2prs, main = "Ackley 2D", names = c("MS", "PRS"), ylab = "Ilość wystąpień")
boxplot(a10ms,a10prs, main = "Ackley 10D", names = c("MS", "PRS"), ylab = "Ilość wystąpień")
boxplot(a20ms,a20prs, main = "Ackley 20D", names = c("MS", "PRS"), ylab = "Ilość wystąpień")
boxplot(r2ms,r2prs, main = "Rastrigin 2D", names = c("MS", "PRS"), ylab = "Ilość wystąpień")
boxplot(r10ms,r10prs, main = "Rastrigin 10D", names = c("MS", "PRS"), ylab = "Ilość wystąpień")
boxplot(r20ms,r20prs, main = "Rastrigin 20D", names = c("MS", "PRS"), ylab = "Ilość wystąpień")
```

